part4-08team/temporary-name

- .gitignore
> feat: 정적 리소스 파일 깃 이그노어 해제

- src/main/java/project/closet/user/entity/Profile.java
> Profile 엔티티 추가

- src/main/java/project/closet/domain/clothes/controller/ClothesController.java
- src/main/java/project/closet/domain/clothes/dto/request/ClothesCreateRequest.java
- src/main/java/project/closet/domain/clothes/dto/response/ClothesAttributeDto.java
- src/main/java/project/closet/domain/clothes/dto/response/ClothesAttributeWithDefDto.java
- src/main/java/project/closet/domain/clothes/dto/response/ClothesDto.java
- src/main/java/project/closet/domain/clothes/dto/response/ClothesDtoCursorResponse.java
- src/main/java/project/closet/domain/clothes/entity/ClothesAttribute.java
- src/main/java/project/closet/domain/clothes/repository/ClothesRepository.java
- src/main/java/project/closet/domain/clothes/service/ClothesService.java
- src/main/java/project/closet/domain/clothes/service/ClothesServiceImpl.java
- src/main/java/project/closet/exception/GlobalExceptionHandler.java
- 의상 등록 API 구현  
- 의상 목록 조회 API 구현  
- 정적 리소스 버전(1.0.4) 페이징 오류로 인해 스크롤 시 다음 페이지 미노출 문제 확인 및 강사님께 보고  
- (참고 자료나 이슈 링크를 입력하세요)
> 의상 등록, 목록 조회 api 구현

- src/main/java/project/closet/dto/request/FollowCreateRequest.java
- src/main/java/project/closet/dto/response/FollowDto.java
- src/main/java/project/closet/dto/response/FollowSummaryDto.java
- src/main/java/project/closet/dto/response/UserSummary.java
- src/main/java/project/closet/exception/ErrorCode.java
- src/main/java/project/closet/exception/follow/FollowException.java
- src/main/java/project/closet/exception/follow/SelfFollowNotAllowedException.java
- src/main/java/project/closet/follower/controller/FollowController.java
- src/main/java/project/closet/follower/controller/api/FollowApi.java
- src/main/java/project/closet/follower/entity/Follow.java
- src/main/java/project/closet/follower/repository/FollowRepository.java
- src/main/java/project/closet/follower/service/FollowService.java
- src/main/java/project/closet/follower/service/basic/BasicFollowService.java
- src/main/java/project/closet/security/SecurityMatchers.java
- src/main/java/project/closet/weather/response/Body.java
- src/main/java/project/closet/weather/response/Header.java
- src/main/java/project/closet/weather/response/Items.java
- src/main/java/project/closet/weather/response/Response.java
- src/main/java/project/closet/weather/response/WeatherApiResponse.java
- src/main/java/project/closet/weather/response/WeatherItem.java
- src/main/java/project/closet/weather/service/basic/WeatherAPIClient.java
- src/main/resources/application.yaml
- src/main/resources/sql/schema.sql
- 팔로우 엔티티 생성
- 팔로우 엔드포인트 매핑
- 팔로우 예외 생성
> 팔로우 엔티티, 엔드포인트 기본 매핑

- src/main/java/project/closet/exception/ClosetException.java
- src/main/java/project/closet/exception/ErrorCode.java
- src/main/java/project/closet/exception/GlobalExceptionHandler.java
- src/main/java/project/closet/exception/feed/FeedException.java
- src/main/java/project/closet/exception/feed/FeedLikeAlreadyExistsException.java
- src/main/java/project/closet/exception/feed/FeedNotFoundException.java
- src/main/java/project/closet/feed/controller/FeedController.java
- src/main/java/project/closet/feed/controller/api/FeedApi.java
- src/main/java/project/closet/feed/service/FeedService.java
- src/main/java/project/closet/feed/service/basic/BasicFeedService.java
- src/main/java/project/closet/follower/entity/FeedLike.java
- src/main/java/project/closet/weather/repository/FeedLikeRepository.java
- src/main/resources/sql/schema.sql
- Feed 좋아요 등록 엔드포인드
- Feed 좋아요 취소 엔드포인트
- 구현하지 않은 엔드포인트 예외 Throw 처리
> Feat Fead 좋아요 등록, 취소 기능 구현

- src/main/java/project/closet/dto/response/CommentDto.java
- src/main/java/project/closet/exception/ErrorCode.java
- src/main/java/project/closet/exception/feed/FeedLikeAlreadyExistsException.java
- src/main/java/project/closet/feed/controller/FeedController.java
- src/main/java/project/closet/feed/controller/api/FeedApi.java
- src/main/java/project/closet/feed/entity/FeedComment.java
- src/main/java/project/closet/feed/repository/FeedCommentRepository.java
- src/main/java/project/closet/feed/repository/FeedLikeRepository.java
- src/main/java/project/closet/feed/service/FeedService.java
- src/main/java/project/closet/feed/service/basic/BasicFeedService.java
- src/main/resources/sql/schema.sql
- Feed Comment 생성 기능 구현 (기존 스키마에서 comment -> content로 변경, user_id -> author_id로 변경)
- 피드 좋아요 중복 예외 관리 이넘 변수명과 에러 메세지 변경
- 피드 댓글 엔티티 매핑
- 기존 FeedLike 레포지터리 패키지 위치 Weather로 잘못 넣었던 것 Feed 패키지로 변경
> Feat Feed에 댓글 생성 기능 구현

- src/main/java/project/closet/domain/clothes/service/ClothesServiceImpl.java
- src/main/java/project/closet/dto/response/UserDto.java
- src/main/java/project/closet/feed/repository/impl/FeedCommentRepositoryImpl.java
- src/main/java/project/closet/follower/repository/FollowRepositoryImpl.java
- src/main/java/project/closet/security/ClosetUserDetails.java
- src/main/java/project/closet/security/jwt/JwtAuthenticationFilter.java
- src/main/java/project/closet/security/jwt/JwtObject.java
- src/main/java/project/closet/security/jwt/JwtService.java
기존 UserDto 객체를 담았는데 필드로 하나씩 가지도록 수정했습니다.
- 관리자 로그인 시 나오지 않는 관리 탭 문제 해결
- 기존 JWT 클레임에 UserDto 객체를 넣었는데, 각 필드를 하나씩 가지도록 수정했습니다.
> Refactor Jwt 토큰에 담는 클레임 수정

- src/main/java/project/closet/feed/service/basic/BasicFeedService.java
- src/main/java/project/closet/storage/S3ContentStorage.java
- s3 presigned Url 생성 로직에 null 처리 추가
- contentType 추가
- 의상 사진 url 매핑에 로직 presigendUrl 생성 로직 추가
> Refactor: s3 presigned Url에 content type 설정 추가, key 널처리

- build.gradle
- src/main/java/project/closet/auth/controller/api/AuthApi.java
- src/main/java/project/closet/config/WebSocketConfig.java
- src/main/java/project/closet/dm/controller/DirectMessageController.java
- src/main/java/project/closet/dm/controller/api/DirectMessageApi.java
- src/main/java/project/closet/dm/entity/DirectMessage.java
- src/main/java/project/closet/dm/repository/DirectMessageRepository.java
- src/main/java/project/closet/dm/service/DirectMessageService.java
- src/main/java/project/closet/dm/service/MessageService.java
- src/main/java/project/closet/dm/service/basic/BasicMessageService.java
- src/main/java/project/closet/dto/request/DirectMessageCreateRequest.java
- src/main/java/project/closet/dto/response/DirectMessageDto.java
- src/main/java/project/closet/dto/response/DirectMessageDtoCursorResponse.java
- src/main/java/project/closet/feed/controller/api/FeedApi.java
- src/main/java/project/closet/follower/controller/api/FollowApi.java
- src/main/java/project/closet/user/controller/api/UserApi.java
- src/main/java/project/closet/weather/controller/api/WeatherApi.java
- src/main/java/project/closet/websocket/MessageWebSocketController.java
- src/main/resources/application.yaml
- src/main/resources/sql/schema.sql
- Websocket Config 파일 생성
- 웹소켓으로 메시지를 받아서 브로드 캐스트하는 기능 구현
- 스프링 웹소켓 의존성 추가
> Feat/dm 웹소켓 이용하여 메시지 송수신 설정

- src/main/java/project/closet/domain/clothes/controller/ClothesController.java
- src/main/java/project/closet/domain/clothes/dto/request/ClothesUpdateRequest.java
- src/main/java/project/closet/domain/clothes/dto/response/ClothesDto.java
- src/main/java/project/closet/domain/clothes/entity/Clothes.java
- src/main/java/project/closet/domain/clothes/entity/ClothesAttribute.java
- src/main/java/project/closet/domain/clothes/service/ClothesService.java
- src/main/java/project/closet/domain/clothes/service/ClothesServiceImpl.java
- src/main/java/project/closet/dto/response/OotdDto.java
- src/main/java/project/closet/exception/ErrorCode.java
- src/main/java/project/closet/exception/GlobalExceptionHandler.java
- src/main/java/project/closet/exception/clothes/ClothesException.java
- src/main/java/project/closet/exception/clothes/ClothesNotFoundException.java
- src/main/resources/sql/schema.sql
- 옷 삭제, 수정 api 추가
- s3 저장 관련 key로 필드명 변경
-  S3ContentStorage 클래스 추가에 따라서 저장과 응답 로직 추가 시켰습니다.
> feat: 옷 삭제, 수정 api 추가, 의상 등록 , 수정 이미지 업로드 및 URL 반환 추가

- src/main/java/project/closet/feed/service/basic/BasicFeedService.java
> refactor: Clothes 필드 변경에 따른 관련 getter 호출명 수정

- src/main/java/project/closet/domain/clothes/service/ClothesServiceImpl.java
> refactor: 옷 등록시 이미지가 없을 경우 null 값이 아니라 빈문자열 저장하게 수정

- src/main/java/project/closet/domain/clothes/service/ClothesServiceImpl.java
- 의상 이미지 업데이트,의상 삭제시 S3 저장된 이미지 삭제
> 의상 이미지 업데이트,의상 삭제시 S3 저장된 이미지 삭제

- src/main/java/project/closet/weather/entity/SkyStatus.java
> Refactor: Sky Status 프론트에 맞게 이넘 수정

- src/main/java/project/closet/domain/clothes/repository/ClothesRepository.java
- src/main/java/project/closet/domain/recommend/TemperatureCategory.java
- src/main/java/project/closet/domain/recommend/controller/RecommendationController.java
- src/main/java/project/closet/domain/recommend/dto/responses/RecommendationDto.java
- src/main/java/project/closet/domain/recommend/service/WeatherOutfitRecommendationService.java
- src/main/java/project/closet/domain/recommend/service/WeatherOutfitRecommendationServiceImpl.java
- src/test/java/project/closet/domain/recommend/TemperatureCategoryTest.java
- src/test/java/project/closet/domain/recommend/controller/RecommendationControllerTest.java
> 의상추천 api 추가

- build.gradle
- src/main/java/project/closet/auth/service/basic/BasicAuthService.java
- src/main/java/project/closet/config/MailConfig.java
- src/main/java/project/closet/mail/MailService.java
- src/main/resources/application.yaml
- src/main/resources/static/password-reset.html
- src/test/java/project/closet/mail/MailServiceIntegrationTest.java
- src/test/java/project/closet/mail/MailServiceTest.java
- src/test/resources/application-test.yaml
- 간단한 텍스트만 보내는 버전으로 실제 메일이 도착하는 기능
- html 파일을 불러와서 비밀번호 초기화 api 에 연결하여 변경된 비밀번호를 메일로 발송하는 기능 구현
> Feat: Mail 발송 기능 구현, 테스트

- src/main/java/project/closet/notification/repository/impl/NotificationRepositoryImpl.java
이전에 수정했던 부분 누락된 entity 인스턴스 변수 수정 후 jpql 적용 수정
> Refactor: 알림 조회 쿼리에서 엔티티 변경으로 where 절 조건문 jpql 수정

- src/main/java/project/closet/auth/controller/AuthController.java
- src/main/java/project/closet/notification/repository/impl/NotificationRepositoryImpl.java
- src/main/java/project/closet/security/ClosetUserDetails.java
> Feat/auth 사용자 엔티티 lock 을 이용해서 계정 잠금 기능 추가

- build.gradle
- src/test/java/project/closet/mail/MailServiceTest.java
> Feat: build 파일에 plane jar 파일 생성되지 않도록 설정, 메일 테스트 disable

- build.gradle
- src/main/java/project/closet/config/MDCLoggingInterceptor.java
- src/main/java/project/closet/config/WebMvcConfig.java
- src/main/java/project/closet/exception/ErrorResponse.java
- src/main/java/project/closet/exception/GlobalExceptionHandler.java
- src/main/resources/application.yaml
- src/main/resources/logback-spring.xml
- MDC 를 이용해 로깅에 요청 정보를 추가했습니다.
- .log 폴더에 로깅 정보가 저장됩니다. 30일 단위
- controllerAdvice에 누락된 validation 예외 발생 핸들러 추가
> Feat/logging 서버 상태를 식별하기 위해서 로깅 설정, validation 예외 핸들러 추가

- src/main/java/project/closet/domain/recommend/dto/responses/ClothesForRecommendDto.java
- src/main/java/project/closet/domain/recommend/dto/responses/RecommendationDto.java
- src/main/java/project/closet/domain/recommend/service/WeatherOutfitRecommendationServiceImpl.java
- src/main/java/project/closet/feed/service/basic/BasicFeedService.java
- API 응답 스펙에 맞게 DTO 수정
- 서명된 URL S3 받아서 DTO에 넣어주도록 로직 수정
> Refactor: OOTD 추천 시 API 응답 스펙 맞지 않는 부분 수정, S3 presined URL 응답하도록 DTO 수정

- docker-compose.yml
> Feat: 로그 파일 롤링docker-compose 볼륨 마운트 설정

- Dockerfile
- build.gradle
- docker-compose.yml
- grafana/provisioning/datasources/prometheus-datasource.yml
- prometheus.yml
- src/main/java/project/closet/weather/service/WeatherService.java
- src/main/java/project/closet/weather/service/basic/BasicWeatherService.java
- src/main/java/project/closet/weather/service/basic/WeatherInitializer.java
- src/main/resources/application.yaml
- 기존 스케줄러에서 시간대, 에러 발생 로그 분석 결과 서버 CPU 고갈 문제가 아닌것 확인
- 정확한 서버 상태를 확인하기 위해서 프로메테우스, 그라파나 컨테이너 추가하여 메트릭 수집
> Feat/actuator Actuator, Prometheus, Grafana 컨테이너 설정 추가

- docker-compose.yml
- src/main/java/project/closet/weather/service/basic/BasicWeatherService.java
- src/main/java/project/closet/weather/service/basic/WeatherAPIClient.java
다음 날씨 데이터가 필요, 날짜가 바뀌기 전에 데이터를 가지기 위해 요청 시간 (3분) 고려해 55분으로 변경
- 스케줄러 시간 변경
- grafana 데이터베이스 서버 스펙이 느려 생기는 동시성 문제를 위해 환경변수 추가
- 줄바꿈
> Refactor: 23시 날씨 데이터가 30분에 없는 경우가 발생해 시간 변경
